on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

name: rhub-check-clang

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/clang16:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--compact-vignettes=gs+qpdf", "--as-cran")'
          check-dir: '"check"'
