on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

name: rhub-check-clang

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/clang16:latest

    steps:
    - actions/checkout@v3

    - name: Install dependencies
      run: |
        R -q -e 'pak::pkg_install(c("deps::.", any::rcmdcheck"), dependencies = TRUE)'

    - uses: r-lib/actions/check-r-package@v2
